### ISSUE TITLE
Practica De Conversiones "Equipo Eduardo Tomas Feria Ortiz"

### ISSUE THREAD

**Issue by Eduardo21620095** [SistemasTecTlaxiaco/ejercicios-team-eduardo-tomas-1as#2]
[PRACTICA1_1AS_EQUIPO_EDUARDO_TOMAS.pdf](https://github.com/SistemasTecTlaxiaco/ejercicios-team-eduardo-tomas-1as/files/7150050/PRACTICA1_1AS_EQUIPO_EDUARDO_TOMAS.pdf)

**Comment by Arlet04** [comment]
Portada 25 puntos
Procedimiento 22 punto "le faltó explicar cada una de las operaciones que realizó (procedimiento)"
Figura, Ilustraciones y fotografías 25 punto 
Resultados y conclusiones 25

**Comment by Arlet04** [comment]
Portada (excelente) contiene todos los datos que se solicitan (25 puntos)
Procedimiento (Bueno) Contiene suficientes ejemplos pero no basta ya que le falto explicar de manera detallada el procedimiento que siguió con cada uno de los mismos (20 puntos)
Figuras, ilustraciones y fotografías (notable) contiene suficientes imágenes aunque faltó explicarlas mas a detalle (22 puntos)
Resultados y conclusiones ( Bueno) le faltó mas contenido a su conclusión (20 puntos)
Total:87 puntos /100
Calificación:17.4% / 20%
Calificado por: Jeanette Arlet Salazar Nicolás

**Comment by josealfredo79** [comment]
Bien hecho y revisado
